services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
  nginx:
    image: macbre/nginx-http3:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:z
      - ./config/localhost.crt:/etc/nginx/ssl/localhost.crt:z
      - ./config/localhost.key:/etc/nginx/ssl/localhost.key:z
    ports:
      - "443:443/tcp"
      - "443:443/udp"
