services:
  postgres:
    image: postgres:16.2-alpine3.19
    restart: "always"
    ports:
      - 9876:5432
    volumes:
      - sockets:/var/run/postgresql:z
      - ./data/postgres:/var/lib/postgresql/data:Z
    env_file:
      - .env

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: "always"
    depends_on:
      - postgres
    volumes:
      - sockets:/run/sockets:z
    env_file:
      - .env

  nginx:
    image: macbre/nginx-http3:latest
    restart: "always"
    depends_on:
      - "backend"
    user: "root"
    volumes:
      - sockets:/run/sockets:z
      - ./config/nginx.conf:/etc/nginx/nginx.conf:Z
      - ./config/localhost.crt:/etc/nginx/ssl/localhost.crt:Z
      - ./config/localhost.key:/etc/nginx/ssl/localhost.key:Z
    ports:
      - "443:443/tcp"
      - "443:443/udp"

volumes:
  sockets:
