[package]
name = "flickers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="flickers"
path = "app/main.rs"

[dependencies]
handlebars = "5.1.2"
rocket = "0.5.0"
